jobs:
- job: build
  displayName: Build
  steps:
  - checkout: self
  - task: CmdLine@2
    name: generateTags
    displayName: 'Generate tags'
    inputs:
      script: | 
        timestampTag=$(date +'%D %T')
        repositoryTag=$(Build.Repository.Name)
        TAGS='{\"Owner\":\"Bicep\", \"DeploymentTimestamp\":\"$timestampTag\", \"DeployRepository\": \"$repositoryTag\"}'
        # TAGS="testinggggggggggggggggggggggggggggggg"
        echo "##vso[task.setvariable variable=tagsString;isOutput=true;isReadOnly=true]$TAGS"
        echo "##vso[task.setvariable variable=tagsStringDebug;isReadOnly=true]$TAGS"                # Only this one is available within the current job
        echo "Tags are: $TAGS"

  - task: qetza.replacetokens.replacetokens-task.replacetokens@6
    displayName: 'Replace Tokens'
    inputs:
      sources: '**/*.bicepparam'
      actionOnMissing: 'warn'
      tokenPrefix: '#{'
      tokenSuffix: '}#'
  
  - task: CmdLine@2
    displayName: 'Print params'
    inputs:
      script: |
        echo "\nprinting tags...\n"
        echo $(tagsStringDebug)
        echo $(tagsStringDebug) | jq

        echo "\nprinting bicepparam files...\n"
        find . -name "*.bicepparam" -exec sh -c 'echo "##########\nFile: $1\n##########"; cat "$1"' sh {} \;
  
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifacts'
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)'
      artifact: '$(Build.DefinitionName)'
