jobs:
- job: build
  displayName: Build
  steps:
  - checkout: self
  - task: CmdLine@2
    name: generateTags
    displayName: 'Generate tags'
    inputs:
      script: |
        timestampTag=$(date +'%D %T')
        repositoryTag=$(Build.Repository.Name)
        echo "##vso[task.setvariable variable=tagsString;isoutput=true;isreadonly=true]{\"Owner\":\"Bicep\", \"DeploymentTimestamp\":\"$timestampTag\", \"DeployRepository\": \"$repositoryTag\"}"

  - task: qetza.replacetokens.replacetokens-task.replacetokens@6
    displayName: 'Replace Tokens'
    inputs:
      sources: '**/*.bicepparam'
      actionOnMissing: 'warn'
      tokenPrefix: '#{'
      tokenSuffix: '}#'
  
  - task: CmdLine@2
    displayName: 'Print params'
    inputs:
      script: |
        echo "\nprinting tags...\n"
        echo $(tagsString)
        echo $(tagsString) | jq

        echo "\nprinting bicepparam files...\n"
        find . -name "*.bicepparam" -exec sh -c 'echo "##########\nFile: $1\n##########"; cat "$1"' sh {} \;
  
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifacts'
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)'
      artifact: '$(Build.DefinitionName)'
