using './webApp.bicep'

param location = '#{location}#'
param appServicePlanName = '#{appServicePlanName}#'
param appServiceSKU = '#{appServiceSKU}#'
param appServiceName = '#{appServiceName}#'
// param tags = '#{tags}#'
param myIPAddress = '#{myIPAddress}#'
param pythonVersion = '#{pythonVersion}#'
param healthCheckPath = '#{healthCheckPath}#'
param vnetName = '#{vnetName}#'
